// react-example/src/pages/Notes.tsx
import { useEffect, useState } from "react";
import Note from "../components/Note";
import { useUser } from "../siteContext";
import { useNavigate } from "react-router-dom";

function Notes() {
  const { user, setUser } = useUser();

  const navigate = useNavigate();

  useEffect(() => {
    if (!user) navigate("/");
  }, [user, navigate]);

  const [notes, setNotes] = useState([
    {
      id: 1,
      title: "Sastanak sa timom",
      description: "Pripremiti pitanja za sastanak sa timom u vezi novog projekta.",
      completed: false,
    },
    {
      id: 2,
      title: "Kupovina namirnica",
      description: "Kupiti sveze voce, povrce i mlecne proizvode u prodavnici.",
      completed: false,
    },
  ]);

  function toggleCompleteNote(id: number) {
    const newNotes = notes.map((note) => {
      if (note.id === id) {
        return {
          ...note,
          completed: !note.completed,
        };
      }
      return note;
    });
    setNotes(newNotes);
  }

  function deleteNote(id: number) {
    const newNotes = notes.filter((note) => note.id !== id);
    setNotes(newNotes);
  }

  function addNote(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();

    const data = new FormData(e.currentTarget);

    const newNote = {
      id: notes.length + 1,
      title: (data.get("title") || "Prazan naslov") as string,
      description: (data.get("description") || "Prazan opis") as string,
      completed: false,
    };

    setNotes([...notes, newNote]);

    e.currentTarget.reset();
  }

  return (
    <div>
      <div>
        <h2>Dobrodosao {user}!</h2>
        <button onClick={() => setUser("")}>Odjavi se</button>
      </div>
      <form onSubmit={addNote}>
        <input name="title" type="text" placeholder="Title" />
        <input name="description" type="text" placeholder="Description" />
        <button type="submit">Add note</button>
      </form>
      <h1>Lista beleski</h1>
      <ul>
        {notes.map((note) => (
          <Note key={note.id} note={note} toggleCompleteNote={toggleCompleteNote} deleteNote={deleteNote} />
        ))}
      </ul>
    </div>
  );
}

export default Notes;

// angular-example/src/app/notes/notes.component.ts
import { Component } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { Router } from '@angular/router';
import { INote } from 'src/types/note';
import { LoginService } from '../login.service';

@Component({
  selector: 'app-notes',
  templateUrl: './notes.component.html',
  styleUrls: ['./notes.component.css'],
})
export class NotesComponent {
  constructor(
    private loginService: LoginService,
    private router: Router,
    private formBuilder: FormBuilder
  ) {}

  notes: INote[] = [
    {
      id: 1,
      title: 'Sastanak sa timom',
      description:
        'Pripremiti pitanja za sastanak sa timom u vezi novog projekta.',
      completed: false,
    },
    {
      id: 2,
      title: 'Kupovina namirnica',
      description: 'Kupiti sveze voce, povrce i mlecne proizvode u prodavnici.',
      completed: false,
    },
  ];

  toggleCompleteNote = (id: number) => {
    this.notes = this.notes.map((note) => {
      if (note.id === id) {
        return {
          ...note,
          completed: !note.completed,
        };
      }
      return note;
    });
  };

  deleteNote = (id: number) => {
    this.notes = this.notes.filter((note) => note.id !== id);
  };

  addNoteForm = this.formBuilder.group({
    title: '',
    description: '',
  });

  addNote = () => {
    const note: INote = {
      id: this.notes.length + 1,
      title: this.addNoteForm.value.title || 'Prazan naslov',
      description: this.addNoteForm.value.description || 'Prazan opis',
      completed: false,
    };
    this.notes = [...this.notes, note];
    this.addNoteForm.reset();
  };

  user$ = this.loginService.user$;

  logout(): void {
    this.loginService.logout();
    this.router.navigate(['/']);
  }
}

<div>
  <h2>Dobrodosao {{ user$ | async }}!</h2>
  <button (click)="logout()">Odjavi se</button>
</div>

<form (ngSubmit)="addNote()" [formGroup]="addNoteForm">
  <input type="text" name="title" placeholder="Title" formControlName="title" />
  <input type="text" name="description" placeholder="Description" formControlName="description" />
  <button type="submit">Add note</button>
</form>
<h1>Lista beleski</h1>
<ul>
  <li *ngFor="let note of notes">
    <app-note
      [note]="note"
      [deleteNote]="deleteNote"
      [toggleCompleteNote]="toggleCompleteNote"
    />
  </li>
</ul>
