// angular-example/src/app/app.component.ts
import { Component } from '@angular/core';
import { INote } from 'src/types/note';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-example';

  notes: INote[] = [
    {
      id: 1,
      title: 'Sastanak sa timom',
      description:
        'Pripremiti pitanja za sastanak sa timom u vezi novog projekta.',
      completed: false,
    },
    {
      id: 2,
      title: 'Kupovina namirnica',
      description: 'Kupiti sveze voce, povrce i mlecne proizvode u prodavnici.',
      completed: false,
    },
  ];
}

<h1>Lista beleski</h1>
<ul>
  <li *ngFor="let note of notes">
    <h2>{{ note.title }}</h2>
    <p>{{ note.description }}</p>
    <p>Status: {{ note.completed ? "Zavrseno" : "Nije zavrseno" }}</p>
    <button>Oznaci kao {{ note.completed ? "Nije zavrseno" : "Zavrseno" }}</button>
    <button>Izbrisi</button>
  </li>
</ul>

// react-example/src/App.tsx
import Note from "./components/Note";
import { INote } from "./types/note";

function App() {
  const notes: INote[] = [
    {
      id: 1,
      title: "Sastanak sa timom",
      description: "Pripremiti pitanja za sastanak sa timom u vezi novog projekta.",
      completed: false,
    },
    {
      id: 2,
      title: "Kupovina namirnica",
      description: "Kupiti sveze voce, povrce i mlecne proizvode u prodavnici.",
      completed: false,
    },
  ];

  return (
    <div>
      <h1>Lista beleski</h1>
      <ul>
        {notes.map((note) => (
          <Note key={note.id} note={note} />
        ))}
      </ul>
    </div>
  );
}

export default App;
