// angular-example/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { LoginService } from '../login.service';
import { FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  constructor(
    private loginService: LoginService,
    private router: Router,
    private formBuilder: FormBuilder
  ) {
    if (this.loginService.userValue) {
      this.router.navigate(['/notes']);
    }
  }

  loginForm = this.formBuilder.group({
    username: ['', Validators.required],
    password: ['', Validators.required],
  });

  login() {
    const { username, password } = this.loginForm.value;

    if (this.loginForm.invalid || !username || !password) {
      alert('Morate uneti korisnicko ime i lozinku.');
      return;
    }

    this.loginService.login(username);
    this.router.navigate(['/notes']);
  }
}

<h1>Login</h1>
<form [formGroup]="loginForm" (submit)="login()">
  <input type="text" placeholder="Username" formControlName="username" />
  <input type="password" placeholder="Password" formControlName="password" />
  <button type="submit">Prijavi se</button>
</form>

// react-example/src/pages/Login.tsx
import { useNavigate } from "react-router-dom";
import { useUser } from "../siteContext";
import { useEffect } from "react";

function Login() {
  const { user, setUser } = useUser();

  const navigate = useNavigate();

  useEffect(() => {
    if (user) navigate("/notes");
  }, [user, navigate]);

  function login(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();

    const data = new FormData(e.currentTarget);

    if (!data.get("username") || !data.get("password")) {
      alert("Morate uneti korisnicko ime i lozinku.");
      return;
    }

    const user = {
      username: data.get("username") as string,
      password: data.get("password") as string,
    };

    setUser(user.username);

    navigate("/notes");
  }

  return (
    <div>
      <h1>Login</h1>
      <form onSubmit={login}>
        <input type="text" placeholder="Username" name="username" />
        <input type="password" placeholder="Password" name="password" />
        <button type="submit">Prijavi se</button>
      </form>
    </div>
  );
}

export default Login;
