// react-example/src/components/Note.tsx
import { INote } from "../types/note";

interface INoteProps {
  note: INote;
  toggleCompleteNote: (id: number) => void;
  deleteNote: (id: number) => void;
}

const Note = ({ note, toggleCompleteNote, deleteNote }: INoteProps) => {
  return (
    <li>
      <h2>{note.title}</h2>
      <p>{note.description}</p>
      <p>Status: {note.completed ? "Zavrseno" : "Nije zavrseno"}</p>
      <button onClick={() => toggleCompleteNote(note.id)}>
        Oznaci kao {note.completed ? "Nije zavrseno" : "Zavrseno"}
      </button>
      <button onClick={() => deleteNote(note.id)}>Izbrisi</button>
    </li>
  );
};

export default Note;

// angular-example/src/app/note/note.component.ts
import { Component, Input } from '@angular/core';
import { INote } from 'src/types/note';

@Component({
  selector: 'app-note',
  templateUrl: './note.component.html',
  styleUrls: ['./note.component.css'],
})
export class NoteComponent {
  @Input() note!: INote;

  @Input() toggleCompleteNote!: (id: number) => void;

  @Input() deleteNote!: (id: number) => void;
}

<h2>{{ note.title }}</h2>
<p>{{ note.description }}</p>
<p>Status: {{ note.completed ? "Zavrseno" : "Nije zavrseno" }}</p>
<button (click)="toggleCompleteNote(note.id)">
  Oznaci kao {{ note.completed ? "Nije zavrseno" : "Zavrseno" }}
</button>
<button (click)="deleteNote(note.id)">Izbrisi</button>
